security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AuthentificatorAuthenticator
            logout:
                path: app_logout  # Route de déconnexion
                target: app_login  # Redirection après déconnexion

    access_control:
    - { path: ^/homeback, roles: ROLE_ADMIN }
    - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/user/profile, roles: [ROLE_ADMIN, ROLE_PROFESSIONNEL, ROLE_AMATEUR] }
    - { path: ^/user/profile, roles: IS_AUTHENTICATED_FULLY }


        
