twig:
<<<<<<< HEAD
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form_div_layout.html.twig'

=======
    file_name_pattern: '*.twig'
>>>>>>> origin/gestion_utilisateur

when@test:
    twig:
        strict_variables: true
