<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Elearning extends \App\Entity\Elearning implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'content_type' => [parent::class, 'content_type', null],
        "\0".parent::class."\0".'content_url' => [parent::class, 'content_url', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'difficulty_level' => [parent::class, 'difficulty_level', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'file_path' => [parent::class, 'file_path', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reclamations' => [parent::class, 'reclamations', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        'categories' => [parent::class, 'categories', null],
        'content_type' => [parent::class, 'content_type', null],
        'content_url' => [parent::class, 'content_url', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'difficulty_level' => [parent::class, 'difficulty_level', null],
        'duration' => [parent::class, 'duration', null],
        'file_path' => [parent::class, 'file_path', null],
        'id' => [parent::class, 'id', null],
        'reclamations' => [parent::class, 'reclamations', null],
        'title' => [parent::class, 'title', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
