<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Workshop extends \App\Entity\Workshop implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'creatorName' => [parent::class, 'creatorName', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'instractor' => [parent::class, 'instractor', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'materialsProvided' => [parent::class, 'materialsProvided', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'targetAudience' => [parent::class, 'targetAudience', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'topicsCovered' => [parent::class, 'topicsCovered', null],
        'creatorName' => [parent::class, 'creatorName', null],
        'date' => [parent::class, 'date', null],
        'duration' => [parent::class, 'duration', null],
        'id' => [parent::class, 'id', null],
        'instractor' => [parent::class, 'instractor', null],
        'location' => [parent::class, 'location', null],
        'materialsProvided' => [parent::class, 'materialsProvided', null],
        'reservations' => [parent::class, 'reservations', null],
        'targetAudience' => [parent::class, 'targetAudience', null],
        'title' => [parent::class, 'title', null],
        'topicsCovered' => [parent::class, 'topicsCovered', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
