<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'elearnings' => [parent::class, 'elearnings', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'interventions' => [parent::class, 'interventions', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'terrains' => [parent::class, 'terrains', null],
        "\0".parent::class."\0".'workshops' => [parent::class, 'workshops', null],
        'elearnings' => [parent::class, 'elearnings', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'interventions' => [parent::class, 'interventions', null],
        'nom' => [parent::class, 'nom', null],
        'password' => [parent::class, 'password', null],
        'prenom' => [parent::class, 'prenom', null],
        'reservations' => [parent::class, 'reservations', null],
        'roles' => [parent::class, 'roles', null],
        'terrains' => [parent::class, 'terrains', null],
        'workshops' => [parent::class, 'workshops', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
