<?php

namespace ContainerGrjyepc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5gOHy5FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5gOHy5F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5gOHy5F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conseilRepository' => ['privates', 'App\\Repository\\ConseilRepository', 'getConseilRepositoryService', true],
        ], [
            'conseilRepository' => 'App\\Repository\\ConseilRepository',
        ]);
    }
}
