<?php

namespace ContainerGrjyepc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MDeOymdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mDeOymd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mDeOymd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'elearning' => ['privates', '.errored..service_locator.mDeOymd.App\\Entity\\Elearning', NULL, 'Cannot autowire service ".service_locator.mDeOymd": it needs an instance of "App\\Entity\\Elearning" but this type has been excluded in "config/services.yaml".'],
        ], [
            'elearning' => 'App\\Entity\\Elearning',
        ]);
    }
}
