<?php

namespace ContainerSYd1xjq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WKSZwNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w_KSZwN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w_KSZwN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'elearningRepository' => ['privates', 'App\\Repository\\ElearningRepository', 'getElearningRepositoryService', true],
        ], [
            'elearningRepository' => 'App\\Repository\\ElearningRepository',
        ]);
    }
}
