<?php

namespace ContainerSYd1xjq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AbIYDVaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.abIYDVa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.abIYDVa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'workshopRepository' => ['privates', 'App\\Repository\\WorkshopRepository', 'getWorkshopRepositoryService', true],
            'workshopReservationChart' => ['privates', 'App\\Chart\\WorkshopReservationChart', 'getWorkshopReservationChartService', true],
        ], [
            'workshopRepository' => 'App\\Repository\\WorkshopRepository',
            'workshopReservationChart' => 'App\\Chart\\WorkshopReservationChart',
        ]);
    }
}
