<?php

namespace ContainerSYd1xjq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NAHqPcUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NAHqPcU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NAHqPcU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conseil' => ['privates', '.errored..service_locator.NAHqPcU.App\\Entity\\Conseil', NULL, 'Cannot autowire service ".service_locator.NAHqPcU": it needs an instance of "App\\Entity\\Conseil" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'conseil' => 'App\\Entity\\Conseil',
            'entityManager' => '?',
        ]);
    }
}
