<?php

namespace ContainerSYd1xjq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElearning3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mDeOymd.App\Entity\Elearning' shared service.
     *
     * @return \App\Entity\Elearning
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mDeOymd": it needs an instance of "App\\Entity\\Elearning" but this type has been excluded in "config/services.yaml".');
    }
}
