<?php

namespace ContainerSYd1xjq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkshopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.04tykP0.App\Entity\Workshop' shared service.
     *
     * @return \App\Entity\Workshop
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.04tykP0": it needs an instance of "App\\Entity\\Workshop" but this type has been excluded in "config/services.yaml".');
    }
}
