<?php

namespace ContainerRixjyAl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5GViE_UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5GViE.U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5GViE.U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conseil' => ['privates', '.errored..service_locator.5GViE.U.App\\Entity\\Conseil', NULL, 'Cannot autowire service ".service_locator.5GViE.U": it needs an instance of "App\\Entity\\Conseil" but this type has been excluded in "config/services.yaml".'],
            'qrCodeGenerator' => ['privates', 'App\\Service\\QrCodeGeneratorService', 'getQrCodeGeneratorServiceService', true],
        ], [
            'conseil' => 'App\\Entity\\Conseil',
            'qrCodeGenerator' => 'App\\Service\\QrCodeGeneratorService',
        ]);
    }
}
