<?php

namespace ContainerRixjyAl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LLLkEueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lLLkEue' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lLLkEue'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.lLLkEue.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.lLLkEue": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'entityManager' => '?',
            'slugger' => '?',
        ]);
    }
}
