<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrjyepc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrjyepc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrjyepc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrjyepc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGrjyepc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Grjyepc',
    'container.build_id' => '41e96690',
    'container.build_time' => 1740971115,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrjyepc');
