<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRixjyAl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRixjyAl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRixjyAl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRixjyAl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRixjyAl\App_KernelDevDebugContainer([
    'container.build_hash' => 'RixjyAl',
    'container.build_id' => 'bb1bc89c',
    'container.build_time' => 1741003615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRixjyAl');
